language: perl
env:
    - PERL_USE_UNSAFE_INC=0
perl:
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
install:
    - cpanm -q --notest Dist::Zilla || (cat /home/travis/.cpanm/build.log; false)
    - dzil authordeps --missing | cpanm -q --notest || (cat /home/travis/.cpanm/build.log; false)
    - dzil listdeps --author --missing | cpanm -q --notest || (cat /home/travis/.cpanm/build.log; false)
script:
    - dzil test --all
